# Generated by Django 6.0.4 on 2026-08-21 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cover_photo',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='about_me',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='class_year',
            field=models.IntegerField(blank=True, choices=[(2004, '2004'), (2005, '2005'), (2006, '2006'), (2007, '2007'), (2008, '2008')], null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='concentration',
            field=models.CharField(blank=True, help_text='Major/Concentration', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='courses',
            field=models.CharField(blank=True, help_text='Courses this semester', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='house',
            field=models.CharField(blank=True, help_text='Dorm/House', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='interested_in',
            field=models.CharField(blank=True, choices=[('women', 'Women'), ('men', 'Men'), ('both', 'Both')], max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='relationship_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('in_relationship', 'In a Relationship'), ('engaged', 'Engaged'), ('married', 'Married')], max_length=20),
        ),
        migrations.CreateModel(
            name='Poke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokes_sent', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokes_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
